variable "AWS_ACCESS_KEY" {}
variable "AWS_SECRET_KEY" {}
variable "ECR_REPOSITORY" {}
variable "ECS_CLUSTER" {}
variable "TASK_ROLE_NAME" {}
variable "TASK_DEFINITION_NAME" {}
variable "CONTAINER_NAME" {}
variable "DOCKER_IMAGE" {}
variable "PORT_NUMBER" {}
variable "VARNAME1" {}
variable "VARNAME2" {}
variable "VARNAME3" {}
variable "VARNAME4" {}
variable "VARNAME5" {}
variable "VARNAME6" {}
variable "VARNAME7" {}
variable "VARNAME8" {}
variable "VARNAME9" {}
variable "VARNAME10" {}
variable "VARVAL1" {}
variable "VARVAL2" {}
variable "VARVAL3" {}
variable "VARVAL4" {}
variable "VARVAL5" {}
variable "VARVAL6" {}
variable "VARVAL7" {}
variable "VARVAL8" {}
variable "VARVAL9" {}
variable "VARVAL10" {}
variable "SECURITY_GROUP_LB" {}
variable "SECURITY_GROUP_ECS" {}
variable "VPC_ID" {}
variable "TARGET_GROUP" {}
variable "HEALTH_CHECK_PATH" {}
variable "LB_NAME" {}
variable "SUBNET1" {}
variable "SUBNET2" {}
variable "SECURITY_POLICY" {}
variable "CERTIFICATE_ARN" {}
variable "ZONE_ID" {}
variable "RECORD_NAME" {}
